import { lazy, Suspense, useMemo, useState } from "react";
import { Activity, ArrowDownRight, ArrowUpRight, Check, ChevronDown, ChevronRight, CircleHelp, Clock3, Crosshair, Eye, Filter, MapPin, Radio, Search, ShieldCheck, SlidersHorizontal, X } from "lucide-react";
import { ClientOnly } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { mockIncidents } from "@/map/mock-incidents";
import type { Incident } from "@/types/incident";

const IncidentMap = lazy(() => import("@/map/IncidentMap"));
type FilterValue = "All incidents" | "Verified" | "Under review" | "Resolved";

function ConfidenceBadge({ value }: { value: number }) {
  return <span className={`confidence ${value >= 90 ? "confidence-high" : value >= 80 ? "confidence-medium" : "confidence-low"}`}><span className="confidence-dot" />{value}% confidence</span>;
}

function IncidentPanel({ incident, onClose }: { incident: Incident | undefined; onClose: () => void }) {
  if (!incident) return <div className="detail-empty"><Crosshair size={24} /><h3>Select an incident</h3><p>Choose a map marker or an incident from the list to inspect its details.</p></div>;
  return <div className="detail-content" key={incident.id}>
    <div className="detail-topline"><span className="eyebrow">INCIDENT DETAILS</span><Button variant="ghost" size="icon" aria-label="Close incident details" title="Close details" onClick={onClose}><X size={17} /></Button></div>
    <div className="detail-title-row"><div><div className="detail-id">{incident.id}</div><h2>{incident.area}</h2><p>{incident.roadSegment}</p></div><span className={`status-pill ${incident.status === "Verified" ? "status-verified" : incident.status === "Resolved" ? "status-resolved" : "status-review"}`}>{incident.status === "Verified" && <Check size={12} />}{incident.status}</span></div>
    {incident.image ? <div className="evidence-image"><img src={incident.image} alt="Illustrative pothole evidence for selected incident" loading="lazy" width={1024} height={768} /><span>REFERENCE IMAGE · DEMO</span></div> : <div className="no-evidence"><Eye size={18} /> No reference image available</div>}
    <div className="detail-confidence"><div><span className="eyebrow">DETECTION CONFIDENCE</span><strong>{incident.confidence}%</strong></div><div className="confidence-track"><span style={{ width: `${incident.confidence}%` }} /></div><p>Based on {incident.sightingCount} matched {incident.sightingCount === 1 ? "sighting" : "sightings"}</p></div>
    <div className="detail-fields"><div><span>Severity</span><strong><span className={`severity-dot severity-${incident.severity.toLowerCase()}`} />{incident.severity}</strong></div><div><span>Sightings</span><strong>{incident.sightingCount} detections</strong></div><div><span>First seen</span><strong>{incident.firstSeen}</strong></div><div><span>Last seen</span><strong>{incident.lastSeen}</strong></div><div><span>Coordinates</span><strong>{incident.latitude.toFixed(4)}, {incident.longitude.toFixed(4)}</strong></div></div>
  </div>;
}

export default function Dashboard() {
  const [selectedId, setSelectedId] = useState<string | null>(mockIncidents[0]?.id ?? null);
  const [filter, setFilter] = useState<FilterValue>("All incidents");
  const [query, setQuery] = useState("");
  const [showFilters, setShowFilters] = useState(false);
  const selected = mockIncidents.find((item) => item.id === selectedId);
  const filtered = useMemo(() => mockIncidents.filter((item) => (filter === "All incidents" || item.status === filter) && `${item.id} ${item.area} ${item.roadSegment}`.toLowerCase().includes(query.toLowerCase())), [filter, query]);
  const verified = mockIncidents.filter((item) => item.status === "Verified").length;
  const highConfidence = mockIncidents.filter((item) => item.confidence >= 90 && item.status !== "Resolved").length;

  return <div className="dashboard">
    <header className="site-header"><div className="header-inner"><div className="brand"><span className="brand-mark"><span /><span /><span /><span /></span><span>Urban<span>Sense</span></span></div><div className="header-center"><span className="header-divider" />ROAD INTELLIGENCE PLATFORM <span className="header-divider" /></div><div className="header-right"><span className="demo-badge">DEMO MODE</span><span className="header-location"><MapPin size={14} /> Bengaluru, IN</span><span className="header-avatar">US</span></div></div></header>
    <main className="main-wrap">
      <div className="page-intro"><div><div className="intro-label"><span className="live-pulse" /> CITY OVERVIEW <span className="intro-slash">/</span> BENGALURU</div><h1>Road incident overview<span className="title-period">.</span></h1><p>Detection intelligence across your city streets.</p></div><div className="snapshot"><Clock3 size={15} /><span>Snapshot · 26 Sep 2026</span><span className="snapshot-separator" /> <span>Illustrative data</span></div></div>
      <div className="metrics"><div className="metric"><div className="metric-heading"><span>Total incidents</span><MapPin size={17} /></div><div className="metric-value">{mockIncidents.length.toString().padStart(2, "0")}<span className="metric-context"><ArrowUpRight size={14} /> Tracked on map</span></div><div className="metric-foot">Across Bengaluru city center</div></div><div className="metric"><div className="metric-heading"><span>Verified incidents</span><ShieldCheck size={18} /></div><div className="metric-value">{verified.toString().padStart(2, "0")}<span className="metric-context metric-context-green"><Check size={14} /> Confirmed</span></div><div className="metric-foot">Matched across multiple sightings</div></div><div className="metric"><div className="metric-heading"><span>High confidence</span><Activity size={18} /></div><div className="metric-value">{highConfidence.toString().padStart(2, "0")}<span className="metric-context metric-context-orange"><ArrowUpRight size={14} /> 90% or above</span></div><div className="metric-foot">Active incidents with strong signals</div></div><div className="metric metric-process"><div className="metric-heading"><span>Detection pipeline</span><Radio size={18} /></div><div className="pipeline"><span>Video</span><ChevronRight size={14} /><span>Detect</span><ChevronRight size={14} /><span>Verify</span><ChevronRight size={14} /><span className="pipeline-final">Map</span></div><div className="metric-foot">From street footage to actionable insight</div></div></div>
      <div className="workspace-heading"><div><span className="eyebrow">SPATIAL VIEW</span><h2>Incident map <span className="heading-count">{filtered.length}</span></h2></div><div className="map-key"><span><i className="key-dot key-high" /> High confidence</span><span><i className="key-dot key-medium" /> Medium</span><span><i className="key-dot key-low" /> Lower / resolved</span></div></div>
      <div className="workspace"><section className="map-panel" aria-label="Incident map"><div className="map-toolbar"><div className="map-region"><Crosshair size={15} /> Central Bengaluru <ChevronDown size={14} /></div><span className="map-toolbar-count">{filtered.length} locations shown</span></div><div className="map-canvas"><ClientOnly fallback={<div className="map-placeholder">Loading map…</div>}><Suspense fallback={<div className="map-placeholder">Loading map…</div>}><IncidentMap incidents={filtered} selected={selected} onSelect={setSelectedId} /></Suspense></ClientOnly></div><div className="map-bottom"><span><span className="map-bottom-indicator" /> OpenStreetMap basemap</span><span>Scroll to browse incidents below <ArrowDownRight size={13} /></span></div></section><aside className="detail-panel" aria-label="Incident details"><IncidentPanel incident={selected} onClose={() => setSelectedId(null)} /></aside></div>
      <section className="incidents-section"><div className="incidents-header"><div><span className="eyebrow">INCIDENT LOG</span><h2>Recent detections <span className="heading-count">{filtered.length}</span></h2></div><div className="list-tools"><label className="search-field"><Search size={16} /><input aria-label="Search incidents" placeholder="Search incidents..." value={query} onChange={(event) => setQuery(event.target.value)} /></label><div className="filter-wrap"><Button variant="outline" onClick={() => setShowFilters(!showFilters)} aria-expanded={showFilters}><SlidersHorizontal size={15} /> {filter === "All incidents" ? "Filter" : filter} <ChevronDown size={14} /></Button>{showFilters && <div className="filter-menu">{(["All incidents", "Verified", "Under review", "Resolved"] as FilterValue[]).map((option) => <Button key={option} variant="ghost" onClick={() => { setFilter(option); setShowFilters(false); }}><span>{option}</span>{filter === option && <Check size={14} />}</Button>)}</div>}</div></div></div>
      <div className="incident-list"><div className="list-columns"><span>INCIDENT / LOCATION</span><span>CONFIDENCE</span><span>SIGHTINGS</span><span>STATUS</span><span>LAST SEEN</span><span /></div>{filtered.length ? filtered.map((incident) => <Button key={incident.id} variant="ghost" className={`incident-row ${selectedId === incident.id ? "incident-row-active" : ""}`} onClick={() => { setSelectedId(incident.id); document.querySelector(".workspace")?.scrollIntoView({ behavior: "smooth", block: "center" }); }}><span className="row-location"><span className="row-icon"><MapPin size={17} /></span><span><strong>{incident.area}</strong><small>{incident.id} · {incident.roadSegment}</small></span></span><span><ConfidenceBadge value={incident.confidence} /></span><span className="row-sightings">{incident.sightingCount.toString().padStart(2, "0")}</span><span><span className={`status-pill ${incident.status === "Verified" ? "status-verified" : incident.status === "Resolved" ? "status-resolved" : "status-review"}`}>{incident.status}</span></span><span className="row-date">{incident.lastSeen.split(", ")[1]}</span><ChevronRight className="row-chevron" size={17} /></Button>) : <div className="list-empty"><Filter size={22} /><strong>No incidents found</strong><p>Try another search or status filter.</p><Button variant="outline" onClick={() => { setQuery(""); setFilter("All incidents"); }}>Clear filters</Button></div>}</div>
      </section>
      <footer className="footer"><span>© 2026 UrbanSense · Road intelligence</span><span><CircleHelp size={14} /> Demo dataset · Not live municipal data</span></footer>
    </main>
  </div>;
}
